### ISSUE TITLE
After the presentViewController  to click Login  CPU rose to 100% 

### ISSUE THREAD

**Issue by Hydra666666** [paypal/PayPal-iOS-SDK#458] opened 2016-09-13 07:36 UTC
### Required Information

- Mode (Mock/Sandbox/Live):Mock
- PayPal iOS SDK Version:2.14.7
- iOS Version and Device (iOS 8.x, iOS 9.3 on an iPhone 6s, etc.):iOS 9.3.4 on an iPhone 6s Plus
- PayPal-Debug-ID(s) (from any logs):

### Issue Description

When the present to PayPalPaymentViewController and click Login ,CPU up to 100%, programs without any reaction no way to pay as well as to present  the next ViewController.

**Comment by bluk** [comment] 2016-09-13 15:03
@Hydra666666 Does this happen with the sample application included in this repository?

**Comment by Hydra666666** [comment] 2016-09-14 02:05
@bluk No，it's doesn't happens on sample demo. In view of the above-mentioned facts on iPhone 4s iOS 8.2 it can work,on iPhone6s iPhone6s Plus iOS 9.0+,CPU up to 100%, programs without any reaction no way to pay as well as to present the next ViewController

**Comment by bluk** [comment] 2016-09-14 02:17
Is there anything else about the environment? Language/region? Any non-standard iOS settings? I can't reproduce this on test devices so was wondering if there's some other setting.

**Comment by pcicp** [comment] 2016-09-20 10:25
@bluk i also found this issue with IQKeyboardManager, see https://github.com/hackiftekhar/IQKeyboardManager/issues/618

**Comment by bluk** [comment] 2016-09-20 15:03
@pcip Thanks, I'm going to close this in favor of #459 because it currently has more information. We are also looking to see what we can do to help this issue.

**Closed by bluk** 2016-09-20 15:03 UTC

**Comment by pcicp** [comment] 2016-09-20 15:52
@bluk i tested again PayPal-iOS-SDK (2.15.1) + IQKeyboardManager (4.0.6). it seems bug only under ios9, ios8 and ios10 are ok.
