### ISSUE TITLE
PayPal SDK: Request has failed with error: UNKNOWN_ERROR - System error. Please try again later. (400)

### ISSUE THREAD

**Issue by SatyanarayanaKV** [paypal/PayPal-iOS-SDK#314] opened 2015-09-01 09:50 UTC
When we test with sand box account details we are unable to pay with card details, We are getting Error message:
PayPal SDK: Request has failed with error: UNKNOWN_ERROR - System error. Please try again later. (400) | PayPal Debug-ID: 00a2b0505b9e0 [sandbox, PayPal iOS SDK 2.11.4]

![screen shot 2015-09-01 at 3 19 12 pm](https://cloud.githubusercontent.com/assets/10413518/9601076/dfac2640-50bc-11e5-9d78-f82578194abe.png)

Thank you Please help me.

**Comment by tomwhipple** [comment] 2015-09-02 22:18
This seems to be working now...

**Comment by tomwhipple** [comment] 2015-09-02 22:40
In general, we the merchant support team can examine what is happening on the backend in both live and sandbox if you [contact them](https://www.paypal-techsupport.com/app/ask) and supply the `debug-id` that is printed to the console log or error response.

But since the problem is no longer happening I am going to close this issue.

**Closed by tomwhipple** 2015-09-02 22:40 UTC
Labels: bug

**Comment by SatyanarayanaKV** [comment] 2015-09-07 07:00
PayPal SDK: Request has failed with error: UNKNOWN_ERROR - System error. Please try again later. (400) | PayPal Debug-ID: cfcee4c1abcba [sandbox, PayPal iOS SDK 2.11.4]

we are getting above  error log please help me.

**Comment by SatyanarayanaKV** [comment] 2015-09-07 10:05
Im using sandbox account details if possible could please list down process details for iOS app.

**Comment by SatyanarayanaKV** [comment] 2015-09-07 13:38
its working now i was created new account and validate its working perfect.Thank you for the response.

**Comment by maksumon** [comment] 2017-01-09 03:00
This issue happening again for test cards... I've not tested with sandbox test account

**Comment by Srikanth-Codebees** [comment] 2017-03-06 05:33
we are getting the below response

PayPal SDK: Request has failed with error: DUPLICATE_REQUEST_ID - System error. Please try again later. (400) | PayPal Debug-ID: 5faf6a0e83a13, 5faf6a0e83a13

**Comment by bluk** [comment] 2017-03-06 15:47
@Srikanth-Codebees For your error, the issue is that domestic direct credit card transactions are not supported in your country. Please see [PayPal REST API Country and Currency Support](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/) for supported countries/currencies. You can contact [PayPal Support](https://developer.paypal.com/support/) for more information.

For anyone else that encounters the `PayPal SDK: Request has failed with error: ` error, please open a new issue with the `PayPal-Debug-ID` as the underlying cause for the error is usually unique.
