### ISSUE TITLE
System error. Please try again later. (400)

### ISSUE THREAD

**Issue by devlonworks** [paypal/PayPal-iOS-SDK#315] opened 2015-09-01 12:02 UTC
In ios everytime i am getting this error .
PayPal SDK: Request has failed with error: UNKNOWN_ERROR - System error. Please try again later. (400) | PayPal Debug-ID: 9cc195909af28 [sandbox, PayPal iOS SDK 2.11.4]

**Comment by tomwhipple** [comment] 2015-09-02 22:17
Sandbox seems to be working for me now...

**Comment by tomwhipple** [comment] 2015-09-02 22:41
In general, we the merchant support team can examine what is happening on the backend in both live and sandbox if you [contact them](https://www.paypal-techsupport.com/app/ask) and supply the `debug-id` that you've shared here.

But since the problem is no longer happening I am going to close this issue.

**Closed by tomwhipple** 2015-09-02 22:41 UTC

**Comment by Srikanth-Codebees** [comment] 2017-03-06 05:09
Hi, can you help me with the same issue
PayPal SDK: Request has failed with error: UNKNOWN_ERROR - System error. Please try again later. (400) | PayPal Debug-ID: a9c4884c870cc

**Comment by xiaoleih41** [comment] 2017-03-28 16:29
Please contact PayPal merchant tech support team at https://www.paypal-techsupport.com/app/ask regarding this issue. Thanks, Xiaolei
