### ISSUE TITLE
Request has failed with error: pp_service_error_empty_response - System error. Please try again later.

### ISSUE THREAD

**Issue by karthickkck315** [paypal/PayPal-iOS-SDK#550] opened 2017-10-16 03:01 UTC
PayPal SDK: Request has failed with error: pp_service_error_empty_response - System error. Please try again later. (503) | PayPal Debug-ID: 55fa5479f00fa, 55fa5479f00fa [sandbox, PayPal iOS SDK 2.16.1]
### General information

* SDK/Library version:  2.16.1
* Environment: Sandbox 
* `PayPal-Debug-ID` values:   PayPal Debug-ID: 55fa5479f00fa, 55fa5479f00fa [sandbox, PayPal iOS SDK 2.16.1]
* iOS Version and Device: ios 10 device 7plus

### Issue description

some time paypal sandobox payment not working and then many times  am getting above error

**Comment by xiaoleih41** [comment] 2017-10-16 16:30
What exact API call are you trying to make? Can you please provide more step by step details for us to pinpoint the cause?

**Comment by xiaoleih41** [comment] 2017-10-26 18:06
Close this issue as the SDK has been deprecated. Please check on the [README.MD](https://github.com/paypal/PayPal-iOS-SDK) for alternative solutions.

**Closed by xiaoleih41** 2017-10-26 18:06 UTC
