### ISSUE TITLE
Paypal ios SDK crash

### ISSUE THREAD

**Issue by nA69** [paypal/PayPal-iOS-SDK#296] opened 2015-07-04 04:12 UTC
when paypal login button clicked in paypalpaymentviewcontroller page application crashed. it shows NSRangeException index 2 is outside of nsarray size 1

device : iphone 4 & 4s 
paypal sdk version:2.11.0

but it works well in iphone 5,5s.6 etc

**Comment by intelliot** [comment] 2015-07-06 23:30
Hi @nA69 - I haven't seen this exact issue yet. Which version of iOS are you running on the iPhone 4 & 4s?

**Comment by nA69** [comment] 2015-07-07 15:04
Ok i am using ios 8 in iphone 4 and ios 7.1.2 in iphone 4s. Same app works
for iphone 5,5s,6 etc.but it throws nsarray index out of bounds exception
in iphone 4 and 4s. this exception throws when i clicked on paypal login
button of paypal home view controller which is provided by paypal ios
sdk.but if i click pay with card it works in iphone 4 and 4s.

Is there anything i need to change in project settings ?
Thanks for your reply.

**Comment by tomwhipple** [comment] 2015-08-11 19:00
If this is readily reproducible, can you share a screenshot from just prior to the crash with a description for what you'd press to make it crash? The payment view controller displays some account specific information, so seeing what you see would be tremendously helpful.

**Comment by nA69** [comment] 2015-08-12 05:32
Thanks everyone for your comment.
I discovered what is the problem.
let consider that  i have an uisegmentcontrol in my project. if i use [UISegmentedControl appearance] setWidth:50 forSegmentAtIndex:3]; this in any place of my project then the problem actually occurs. i think in paypal login page has an uisegment control which has two items "Email" and "Phone".
but i try to set width for segment at index 3.

when i remove [UISegmentedControl appearance] setWidth:50 forSegmentAtIndex:3]; this line from my project then problem do not appear.

**Comment by romk1n** [comment] 2015-08-12 05:34
@nA69 please check this [note](https://github.com/paypal/PayPal-iOS-SDK#usability)

**Comment by tomwhipple** [comment] 2015-08-12 16:28
Thanks for that pointer @romk1n. As you say, changing the appearance of the UI is not supported, so I'm going to close this as not a bug.

**Closed by tomwhipple** 2015-08-12 16:28 UTC
Labels: bug
