### ISSUE TITLE
Failed to Pod update to latest version 

### ISSUE THREAD

**Issue by ywqqqqq** [paypal/PayPal-iOS-SDK#494] opened 2016-12-26 07:22 UTC
1.
I try to update the SDK version with Cocoapods using "pod update PayPal-iOS-SDK --no-repo-update". But it not update to newest version SDK.
I capture the log below.
![image](https://cloud.githubusercontent.com/assets/17809646/21477640/a50b4b4a-cb7e-11e6-95c4-7dddf3dda91a.png)
![image](https://cloud.githubusercontent.com/assets/17809646/21477647/ac74ff98-cb7e-11e6-9602-3eb3a4f3c66e.png)

The project Podfile show blow
platform :ios, '8.0'
inhibit_all_warnings!
target 'IOS_CLIENT'

pod 'PayPal-iOS-SDK'

So how could I update to the version like v2.16.1 via Cocoapod.
If anything I miss?

2.
When I update to the v.2.14.4, it takes a long time installing and after that show error message like below.
![image](https://cloud.githubusercontent.com/assets/17809646/21478652/894aa108-cb88-11e6-900f-91afb519b64d.png)
I have tried third times , but it has turned to the same error.

Thanks

**Comment by bluk** [comment] 2017-01-04 16:07
For the first question, with the latest versions of CocoaPods, you should do a `pod repo update` to get the latest Podspecs locally which would contain all the latest versions.

For the second question, this is a duplicate of https://github.com/paypal/PayPal-iOS-SDK/issues/479 . If you can specify a specific version in your Podfile or use the local repository, you may be able to workaround the issue but it is due to the large repository size for the binaries.

**Closed by bluk** 2017-01-04 16:07 UTC
