### ISSUE TITLE
Crash IOS 9 opening the UI

### ISSUE THREAD

**Issue by ferhelsing** [paypal/PayPal-iOS-SDK#332] opened 2015-09-22 05:45 UTC
I'm getting this while trying to invoke the paypal ui for payment, the code was running fine on ios 8.4, i'm using the latest SDK now on the XCODE 7/ios 9.
The app is using this configuration: 
payPalConfig.languageOrLocale = "es_MX" ( i've change the locale to en_US, but the same problem occurs).
And i've added the NSAppTransportSecurity  with "paypal.com" to my info.plist.

2015-09-21 22:36:06.089 A la carta[1173:17579] *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[NSTaggedPointerString getCharacters:range:]: Range {0, 7} out of bounds; string length 4'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000102c95f65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000101e39deb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000102c95e9d +[NSException raise:format:] + 205
	3   CoreFoundation                      0x0000000102c816aa -[NSTaggedPointerString getCharacters:range:] + 394
	4   CoreFoundation                      0x0000000102b6ef5a CFStringCompareWithOptionsAndLocale + 2970
	5   CoreFoundation                      0x0000000102c8200b -[NSTaggedPointerString compare:options:range:locale:] + 219
	6   Foundation                          0x00000001019d23d7 -[NSString compare:options:range:] + 29
	7   A la carta                          0x000000010040072f __53-[PPZebraLocalizer localizeString:adaptedForCountry:]_block_invoke + 60
	8   CoreFoundation                      0x0000000102bc51cb -[NSArray indexOfObject:inSortedRange:options:usingComparator:] + 491
	9   A la carta                          0x0000000100400474 -[PPZebraLocalizer localizeString:adaptedForCountry:] + 426
	10  A la carta                          0x0000000100400ee4 PPZebraLocalizedStringWithAlert + 1044
	11  A la carta                          0x00000001003ef434 +[PPZebraUI localizedStringForKey:adaptedForCountry:] + 140
	12  A la carta                          0x00000001003f0472 +[PPZebraUI cancelBarButtonWithTarget:withAction:] + 88
	13  A la carta                          0x00000001003de2f1 -[PPDeviceCheckViewController viewDidLoad] + 292
	14  UIKit                               0x0000000103dfe931 -[UIViewController loadViewIfRequired] + 1344
	15  UIKit                               0x0000000103dfec7d -[UIViewController view] + 27
	16  UIKit                               0x0000000103e4f612 -[UINavigationController preferredContentSize] + 194
	17  UIKit                               0x0000000103dd6018 -[UIPresentationController preferredContentSizeDidChangeForChildContentContainer:] + 59
	18  UIKit                               0x0000000103dd24ef __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 95
	19  UIKit                               0x0000000103c7f4be _runAfterCACommitDeferredBlocks + 317
	20  UIKit                               0x0000000103c917ee _cleanUpAfterCAFlushAndRunDeferredBlocks + 95
	21  UIKit                               0x0000000103c9d4e6 _afterCACommitHandler + 90
	22  CoreFoundation                      0x0000000102bc19d7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	23  CoreFoundation                      0x0000000102bc1947 __CFRunLoopDoObservers + 391
	24  CoreFoundation                      0x0000000102bb759b __CFRunLoopRun + 1147
	25  CoreFoundation                      0x0000000102bb6e98 CFRunLoopRunSpecific + 488
	26  GraphicsServices                    0x00000001078bcad2 GSEventRunModal + 161
	27  UIKit                               0x0000000103c73676 UIApplicationMain + 171
	28  A la carta                          0x000000010032c59d main + 109
	29  libdyld.dylib                       0x000000010584c92d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by bluk** [comment] 2015-09-22 15:07
Investigating the locale issue. BTW, I don't think you need the NSAppTransportSecurity Info.plist exceptions for paypal.com but if you see that as an issue, please let me know.

**Comment by tomwhipple** [comment] 2015-09-22 15:15
The PayPal endpoints used by the SDK comply with the app transport security requirement.

**Comment by tomwhipple** [comment] 2015-09-22 15:21
This looks like a duplicate of #310, so we will use that issue for tracking and close this one.

**Closed by tomwhipple** 2015-09-22 15:21 UTC
