### ISSUE TITLE
The SDK does not work

### ISSUE THREAD

**Issue by mogra** [paypal/PayPal-iOS-SDK#313] opened 2015-08-31 02:42 UTC
This SDK sucks, can not be worse. after all the test , everything shows ok, we published the new version, but then the buyers can not make payment , this problem last about 30 hours（ see the screenshot below.). Because of these issue, we got lots of bad comments from google play and AppStore. But this morning the problem went away by itself, can make payment now.  This is not stable , don’t know when will have this problem again. And so does Android version.
![img_0482](https://cloud.githubusercontent.com/assets/5575327/9571225/f3371558-4fcc-11e5-9b29-abab66f98db6.PNG)

**Comment by tomwhipple** [comment] 2015-09-02 22:39
In general, we the merchant support team can examine what is happening on the backend if you [contact them](https://www.paypal-techsupport.com/app/ask) and supply the `debug-id` that is printed to the console log or error response.

But since the problem is no longer happening I am going to close this issue.

**Closed by tomwhipple** 2015-09-02 22:39 UTC
